[client]
showErrorDetails = true
runOnSave = true

[logger]
level = "info"

[theme]
primaryColor = "#1a237e"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#31333F"
font = "sans serif"
